# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

## Overrides for generated resource names
# See templates/_helpers.tpl
# nameOverride:
# fullnameOverride:

Master:
  ServiceType: ClusterIP
  # ContainerEnv:
  #   - name: CASC_JENKINS_CONFIG
  #     value: https://git.cias.one/devops/ansible/raw/master/ansible.cfg
  # List of plugins to be install during Jenkins master start
  InstallPlugins:
    - kubernetes:1.13.0
    - workflow-aggregator:2.6
    - workflow-job:2.26
    - credentials-binding:1.16
    - git:3.9.1
    - greenballs:1.15
    - configuration-as-code:1.2
    - job-dsl:1.70
    - configuration-as-code-support:1.2
    - role-strategy:latest
  # Used to approve a list of groovy functions in pipelines used the script-security plugin. Can be viewed under /scriptApproval
  ScriptApproval:
    - "method groovy.json.JsonSlurperClassic parseText java.lang.String"
    - "new groovy.json.JsonSlurperClassic"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods leftShift java.util.Map java.util.Map"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods split java.lang.String"
  CustomConfigMap: false

Persistence:
  Enabled: false

## Install Default RBAC roles and bindings
rbac:
  install: true
  serviceAccountName: jenkins-master
  # RBAC api version (currently either v1beta1 or v1alpha1)
  apiVersion: v1beta1
  # Cluster role reference
  roleRef: admin
  # Role kind (RoleBinding or ClusterRoleBinding)
  roleBindingKind: ClusterRoleBinding
